### ISSUE TITLE
Command + click within a selection has everything start again

### ISSUE THREAD

**Issue by onassar** [luckyseven/jquery-multiselector#2]
Again, modelling after OSX, this is how I'd expect things to behave:
https://screencast.com/t/ECvSV1yIiAIe

Notice that the "pivot point" after the deselection via Command+click is the next "element". Namely, the `Public` folder

This is how things behave in the demo:
https://screencast.com/t/G0MFtjNiK

Would be great to have this work the same way as OSX (and I'm guessing, Windows?)

**Comment by luckyseven** [comment]
Working on it!

**Comment by luckyseven** [comment]
I've improved some selection combos. It's not 100% identical as OSX but i think it's a good behavior. Try it and let me know! ;)
