### ISSUE TITLE
Deselecting

### ISSUE THREAD

**Issue by mcgrailm** [luckyseven/jquery-multiselector#3]
This might be more of a question than an issue not sure. 

When i click on an item without using the command key it deselects everything else. is there a way to prevent that from happening , i want it to act like im holding the command key unless i'm holding shift key, is that possible ?

Mike

**Comment by luckyseven** [comment]
Hi Mike,
i've published a new version of the plugin some minutes ago (v.1.2.0). In this version, i've added a fourth parameter on `onSelectionStart` and `onSelectionEnd` callbacks, so you can use them to simulate keys holding this way:
```javascript
$("...").multiSelector({
    onSelectionStart: function(list, parent, element, event)
    {
        //Holding the command key
        event.metaKey = true;

        //Holding the ctrl key
        event.ctrlKey = true;

        //Holding the shift key
        event.shiftKey = true;
    }
});
```

So, in your case, you should use `event.metaKey = true` to reach your goal. 

Hope it helps!

Alberto
